"use client"

import { motion, useInView } from "framer-motion"
import { useRef, useState, useEffect } from "react"
import { AlertTriangle, FolderOpen, MessageSquarePlus, CalendarClock, Layers, Sliders } from "lucide-react"

const features = [
  {
    icon: AlertTriangle,
    title: "Instant Urgency Detection",
    description: "AI identifies time-sensitive emails from professors, recruiters, and VIPs in real-time",
    color: "coral"
  },
  {
    icon: FolderOpen,
    title: "Smart Categorization",
    description: "Automatically organize emails into meaningful categories with custom labels",
    color: "teal"
  },
  {
    icon: MessageSquarePlus,
    title: "AI Draft Replies",
    description: "Get intelligent response suggestions generated by Gemini AI in seconds",
    color: "gold"
  },
  {
    icon: CalendarClock,
    title: "Deadline Tracking",
    description: "Never miss due dates - automatic extraction and tracking of deadlines",
    color: "teal"
  },
  {
    icon: Layers,
    title: "30-Min Digests",
    description: "Optional periodic summaries of non-urgent emails to reduce noise",
    color: "coral"
  },
  {
    icon: Sliders,
    title: "Custom Rules",
    description: "Define your own priorities, filters, and automation workflows",
    color: "gold"
  },
]

const colorClasses = {
  teal: {
    bg: "bg-teal/10",
    text: "text-teal",
    border: "border-teal/20",
    glow: "shadow-teal/5"
  },
  coral: {
    bg: "bg-coral/10",
    text: "text-coral",
    border: "border-coral/20",
    glow: "shadow-coral/5"
  },
  gold: {
    bg: "bg-gold/10",
    text: "text-gold",
    border: "border-gold/20",
    glow: "shadow-gold/5"
  },
}

function FeatureCard({ feature, index }: { feature: typeof features[0]; index: number }) {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: "-100px" })
  const [mounted, setMounted] = useState(false)
  const colors = colorClasses[feature.color as keyof typeof colorClasses]

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <motion.div
      ref={ref}
      initial={false}
      animate={mounted && isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 40 }}
      transition={{ duration: 0.6, delay: index * 0.1 }}
      className={`group relative p-6 rounded-2xl bg-card border border-border hover:border-${feature.color}/30 transition-all duration-300 hover:shadow-xl ${colors.glow}`}
    >
      {/* Icon */}
      <div className={`w-12 h-12 rounded-xl ${colors.bg} ${colors.text} flex items-center justify-center mb-4 transition-transform duration-300 group-hover:scale-110`}>
        <feature.icon className="w-6 h-6" />
      </div>

      {/* Content */}
      <h3 className="text-xl font-semibold text-foreground mb-2" suppressHydrationWarning>{feature.title}</h3>
      <p className="text-muted-foreground leading-relaxed" suppressHydrationWarning>{feature.description}</p>

      {/* Hover glow effect */}
      <div className={`absolute inset-0 rounded-2xl ${colors.bg} opacity-0 group-hover:opacity-50 transition-opacity duration-300 -z-10 blur-xl`} />
    </motion.div>
  )
}

export function FeaturesGridSection() {
  const sectionRef = useRef(null)
  const isInView = useInView(sectionRef, { once: true, margin: "-100px" })
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <section className="relative py-24 lg:py-32 overflow-hidden">
      {/* Angled divider top */}
      <div className="absolute top-0 left-0 right-0 h-24 bg-background transform -skew-y-2 origin-top-left -translate-y-12" />

      <div className="container mx-auto px-6 lg:px-12 relative z-10">
        {/* Section header */}
        <motion.div
          ref={sectionRef}
          initial={false}
          animate={mounted && isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
          transition={{ duration: 0.6 }}
          className="text-center max-w-3xl mx-auto mb-16"
        >
          <span className="inline-block px-4 py-1.5 rounded-full bg-muted text-muted-foreground text-sm font-medium mb-4">
            Features
          </span>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground mb-6 text-balance" suppressHydrationWarning>
            Powerful features for{" "}
            <span className="text-teal">inbox mastery</span>
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed" suppressHydrationWarning>
            Everything you need to stay on top of your email without the overwhelm
          </p>
        </motion.div>

        {/* Features grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <FeatureCard key={feature.title} feature={feature} index={index} />
          ))}
        </div>
      </div>

      {/* Angled divider bottom */}
      <div className="absolute bottom-0 left-0 right-0 h-24 bg-background transform skew-y-2 origin-bottom-right translate-y-12" />
    </section>
  )
}
